var projs_new = [

    {
        index: 0,
        show_home: true,
        show_menu: true,
        html_page: '/nobody.html',
        title: 'Nobody: / O Povo: ódio, medo e indignação',
        date: 'July 19, 2021 00:00:00',
        desc: ' explora o contraste entre a realidade e o imaginário fabricado pelo discurso de extrema-direita em Portugal. Um ensaio que reflecte sobre o avanço do discurso extremista e que parte das alterações do espaço mediático e dos novos modos de propaganda digital e uma narrativa que procura desenhar.',
        desc_menu: 'Independent Publication',
        year: '2021',
        text: "is a magazine all about contrasts, the duality of two separate ends, the wind and the storm. The name Just the Wind came from a Magic the Gathering™ card with the same name. The card name comes to show a moment where we ask “what was it?” and respond with: “nothing, just the wind”.<p>This first issue is about humanity and its next stages, how to evolve a society and how we could reach the pinnacle of the human condition. The human being as the center of all the universe, or the possibility that of not ever being...</p><p>With the Wind and the Storm, we want to create a blur between the real insignificance and the insignificance of the real, revealing the big picture as a drama but always keeping in mind that, like it says in the card’s flavor text, “There’s nothing to worry about”.</p>",
        text_pos: "three",
        collaboration: '',
        thumbnails: ["/image/work/nobody/nobody-1.jpg", "/image/work/nobody/nobody-2.jpg"],
        thumbnails_pos: ["two-left", "two-right"],
        thumbnails_menu: '/image/work/nobody/nobody-2.jpg',
        images: [
            "/image/work/nobody/nobody-3.jpg", 
            "/image/work/nobody/nobody-1.jpg", 
            "<br>",
            "/image/work/nobody/nobody-2.jpg", 
            "/image/work/nobody/nobody-7.jpg", 
            "/image/work/nobody/nobody-6.jpg", 
            "/image/work/nobody/nobody-5.jpg", 
            "<br>",
            "/image/work/nobody/nobody-8.jpg", 
            "/image/work/nobody/nobody-4.jpg", 
            ],
        images_pos: [
            "three", 
            "two-left", 
            "",
            "one-right",
            "two-left", 
            "two-left", 
            "two-left", 
            "",
            "one-right",
            "two-left", 
        ],
        new: true,
        free: false,
        buy: false,
    },

    {
        index: 1,
        show_home: true,
        show_menu: true,
        html_page: '/nobody.html',
        title: 'InPuslos',
        date: 'July 19, 2021 00:00:00',
        desc: ' explora o contraste entre a realidade e o imaginário fabricado pelo discurso de extrema-direita em Portugal. Um ensaio que reflecte sobre o avanço do discurso extremista e que parte das alterações do espaço mediático e dos novos modos de propaganda digital e uma narrativa que procura desenhar.',
        desc_menu: 'Independent Publication',
        year: '2021',
        text: "<p><i>Just the Wind</i> is a magazine all about contrasts, the duality of two separate ends, the wind and the storm. The name Just the Wind came from a Magic the Gathering™ card with the same name. The card name comes to show a moment where we ask “what was it?” and respond with: “nothing, just the wind”.</p><p>This first issue is about humanity and its next stages, how to evolve a society and how we could reach the pinnacle of the human condition. The human being as the center of all the universe, or the possibility that of not ever being...</p><p>With the Wind and the Storm, we want to create a blur between the real insignificance and the insignificance of the real, revealing the big picture as a drama but always keeping in mind that, like it says in the card’s flavor text, “There’s nothing to worry about”.</p>",
        text_pos: "three",
        collaboration: '',
        thumbnails: ["/image/work/nobody/nobody-1.jpg", "/image/work/nobody/nobody-2.jpg"],
        thumbnails_pos: ["two-left", "two-right"],
        thumbnails_menu: '/image/work/nobody/nobody-1.jpg',
        images: ["/image/work/nobody/nobody-1.jpg", "/image/work/nobody/nobody-2.jpg"],
        images_pos: ["two-left", "two-right"],
        new: true,
        free: false,
        buy: false,
    },

    {
        index: 2,
        show_home: true,
        show_menu: true,
        html_page: '/nobody.html',
        title: 'APIP',
        date: 'July 19, 2021 00:00:00',
        desc: ' explora o contraste entre a realidade e o imaginário fabricado pelo discurso de extrema-direita em Portugal. Um ensaio que reflecte sobre o avanço do discurso extremista e que parte das alterações do espaço mediático e dos novos modos de propaganda digital e uma narrativa que procura desenhar.',
        desc_menu: 'Independent Publication',
        year: '2021',
        text: "<p><i>Just the Wind</i> is a magazine all about contrasts, the duality of two separate ends, the wind and the storm. The name Just the Wind came from a Magic the Gathering™ card with the same name. The card name comes to show a moment where we ask “what was it?” and respond with: “nothing, just the wind”.</p><p>This first issue is about humanity and its next stages, how to evolve a society and how we could reach the pinnacle of the human condition. The human being as the center of all the universe, or the possibility that of not ever being...</p><p>With the Wind and the Storm, we want to create a blur between the real insignificance and the insignificance of the real, revealing the big picture as a drama but always keeping in mind that, like it says in the card’s flavor text, “There’s nothing to worry about”.</p>",
        text_pos: "three",
        collaboration: '',
        thumbnails: ["/image/work/nobody/nobody-1.jpg", "/image/work/nobody/nobody-2.jpg"],
        thumbnails_pos: ["two-left", "two-right"],
        thumbnails_menu: '/image/work/nobody/nobody-3.jpg',
        images: ["/image/work/nobody/nobody-1.jpg", "/image/work/nobody/nobody-2.jpg"],
        images_pos: ["two-left", "two-right"],
        new: true,
        free: false,
        buy: false,
    },


    
    
    
]